### PR TITLE
Feature

### PR DESCRIPTION
**Pull request by cgcarlosg**
Member-Only
In this project, we create an application using ruby on rails and devise gem

-The purpose is to show the mastery using devise gem
-The application consists in create a user that can sign-in, log-in and make posts
-Post views using Devise to retrieve the current user

### CODE REVIEW

**Review by Temmarie — CHANGES_REQUESTED** [review]
## Changes Required! :recycle:

### Hi @cgcarlosg and @carlos-ssh  ! :wave: :wave:

#### You have done well so far :clap: However, there are changes required for you to make in order for this project to be approved. Kindly work on them and submit them for another code review.


**Recommended**

- [x] I, unfortunately, could not run your project due to some migration issues from your end. I got this error after I ran the migration.
```
Caused by:
SQLite3::SQLException: no such table: posts
```
- Routes
- [ ] It creates the application routes using resources :posts, only: [:new, :create, :index] ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/posts_routes_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication))
- PostsController
- [ ] It initializes an empty post `@post = Post.new` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/posts_new_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication))


**Optional Changes**
- [ ] A helper method to check if a user is signed_in? can be handy here.
```ruby
# must be a helper method to be used in views
helper_method :signed_in?
def signed_in?
  !current_user.nil?
end
```

- [ ] It displays Flash messages for unsuccessful actions.

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

**Comment by carlos-ssh** [comment]
Hi! we work on this changes:
- We work on issues Caused by: SQLite3::SQLException: no such table: posts.
- We create the application routes using resources :posts, only: [:new, :create, :index].
- and work with a rule on empty post @post = Post.new (nil).
- Create a helper method to check if a user is signed_in?.

Greetings.

Carlos-SSH

**Review by teekaytech — CHANGES_REQUESTED** [review]
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello team :wave:

__You've done really well so far :clap: 
However, some changes are required before this project can be approved. Please check my comments below and fix them as appropriate.__

**[ REQUIRED CHANGES ]**

- [ ] Always follow the project specification. It will save you a lot of time and will make your development faster. 
- You might have your reasons for changing posts to events. However, It is not the best practice to completely change the name of entities in your project. There are reasons why the project specification (on The Odin Project) clearly stated that you should use posts and not events.
- Also, this project review is based on user and post entities. Code snippets and review process is entirely tailored towards those models and to avoid ambiguity, it is better to leave it that way.

- [ ] Logged in users cannot access the posts show page.
- When a user is logged in, they can no longer access the posts show page. Therefore, there's no way to check if logged in users actually see each post's author.

- [ ] Posts(events) routes should be created using `resources :posts, only: [:new, :create, :index]`.
- [ ] The posts_controller(events_controller) should use `before_action` to restrict access to the `:new` and `:create` methods  (uses ApplicationController helper method) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/before_action_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication)).
- [ ] Kindly double-check the project specifications on [The Odin Project](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication#project-members-only) to ensure that you're not missing out on any of the instructions.


* * *
**Please make the required changes and submit another review request when you are done.**

* * *

**Taofeek Olalere
[Twitter](https://twitter.com/ola_lere) | [Github](https://github.com/teekaytech) | @taofeekolalere on Slack**
__Happy Coding :smiley:__

**Comment by cgcarlosg** [comment]
Good evening
You are talking about events
We really do not understand   . that
What events?? Do you have a screenshot?
We see the behavior of our app working, could you explain better the issues please?

**Review by javitocor — CHANGES_REQUESTED** [review]
# STATUS CHANGES REQUIRED 🛑 

Hello team! 👋 
A great job so far in this project 👍 
However, we still need to make some changes to get it approved 💪 
Kindly check my comments below 👇  apply the changes and resubmit your project for a new code review ⏩ 
Good luck! 😺 
## Mandatory changes
- Your app throws an error when launching the server, 'Webpack not found', kindly fix it
- Posts(events) routes should be created using resources :posts, only: [:new, :create, :index]. It is a good practice and good security to add only routes you re using
- Remove all unnecessary code in your controller since you are not using it. ie. json response and actions you are not using
- Kindly remove logic in your views, you should use the application controller to manage that. 
the author is displayed only if a user is signed in (uses ApplicationController helper method) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/posts_index_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication))
- Make your readme file looks professional, add a description, add a screenshot, I guess user needs to run db:migrate, kindly add clear instructions to run the project, make your authors section more readable by adding each field in a different line and add the proper links to them, add acknowledgements section...
- Improve your commits, and both authors should have the same number of commits or similar

**Review by arslanbisharat — APPROVED** [review]
# Approved :smile: 

Hello Developer :wave:

I just reviewed your project and I am very happy to inform you that your project is approved.
Congratulations on achieving this milestone in your career. :clap:


_I am looking forward to seeing your next project._

Stay safe and give me a smile 😇

### Happy Coding
------------------------------------------------------------------------------------------------
**Regards,
Arslan Bisharat
slack: arslanbisharat**

**Pull request closed without merging**
